name: bassliner
description: Bassline Editor for the TD-3
publish_to: 'none'
version: 2.0.3+28

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command:
    path: ../FlutterMidiCommand
  flutter_svg: ^2.0.5
  intl: ^0.18.1
  path_provider: ^2.0.15
  provider: ^6.0.5
  rxdart: ^0.27.7
  security_scoped_resource: #^0.0.1
    #path: ../security_scoped_resource
    git:
      url: https://github.com/intonarumori/security_scoped_resource.git
      ref: 162b091ea28c5fad381cddc909117ed8f102fb91
  shared_preferences: ^2.1.1
  uni_links: ^0.5.1
  url_launcher: ^6.1.11
  watcher:
    #path: ../watcher
    git:
      url: https://github.com/intonarumori/watcher.git
      ref: 8da8beb

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - 'assets/BasslineLogoOutline.svg'
    - 'assets/DmfLogo.svg'
    - 'assets/FolderIcon.svg'
    - 'assets/iPhoneIcon.svg'
    - 'assets/PlusIcon.svg'
    - 'assets/OctaveDownIcon.svg'
    - 'assets/OctaveMiddleIcon.svg'
    - 'assets/OctaveUpIcon.svg'
    - 'assets/QuestionMarkIcon.svg'
    - 'assets/RefreshIcon.svg'
    - 'assets/RotateLeftIcon.svg'
    - 'assets/RotateRightIcon.svg'
    - 'assets/StepSelectionIcon.svg'
    - 'assets/TD3Icon.svg'
